= Authentication
[#authentication]
:navtitle: Authentication
:listing-caption: Listing

The `podman-maven-plugin` currently supports one method of authentication, which is by providing authentication details via the Maven settings file.

== Maven Settings
[#mavensettings]
:navtitle: Maven Settings

Before you start using this plugin, you must configure the registries in your Maven settings file. The first step of `podman-maven-plugin`, before any of the goals is executed, is to authenticate you with all the registries that are configured in your `pom.xml`.

WARNING: The id of the server **must** match the registries configured in the plugin (see below). The plugin will fail if credentials are missing for any of the provided registries.

WARNING: This plugin will also fail if there are no registries configured, but authentication is not skipped. Please refer to the table below for all configuration options.

.Excerpt of a Maven Settings file.
[source,XML]
----
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          https://maven.apache.org/xsd/settings-1.0.0.xsd">

    <servers>
        <server>
            <id>container-registry.host.com</id>
            <username>username</username>
            <password>password</password>
        </server>
        <server>
            <id>container-registry.anotherhost.com:12345</id>
            <username>username</username>
            <password>{gsuybjVYiL4HK1S++3xiE9sHnHtzRGBlajGkQE5IH78=}</password> <!--.-->
        </server>
    </servers>

    <!-- Other settings omitted -->

</settings>
----
<.> Both encrypted and unencrypted passwords are supported.