= Authentication
[#authentication]
:navtitle: Authentication
:listing-caption: Listing

The first step of `podman-maven-plugin`, before any of the goals is executed, is to authenticate you with all the registries that are configured in your `pom.xml`. The `podman-maven-plugin` currently supports three methods of authentication:

* Authentication via Podman's default authentication file;
* Authentication via Docker authentication file.
* Authentication via Maven settings;

This plugin will use these mechanisms in the order listed.

NOTE: Registries listed in the Maven Settings are used for authentication. Registries listed in either the Podman's default auth file, or the Docker config file are assumed to be already authenticated.

== Podman's authentication file
[#podmanauth]
:navtitle: Podman authentication

The first method of authentication that is supported by this plugin is the default authentication mechanism of Podman.
The default authentication mechanism is the `auth.json` file located at `$XDG_RUNTIME_DIR/containers/`.

An `auth.json` file is automatically created by Podman when performing a `podman login <registry>` on the command line. Podman will then use this file when performing future commands.

.Sample Podman auth config.
[source,json]
----
{
	"auths": {
		"registry.example.com": {
			"auth": "bGV4OnRlc3Q="
		}
	}
}
----

== Docker configuration file
[#dockerauth]
:navtitle: Docker authentication

The second method of authentication is by using Docker's configuration file. This file is located at `~/.docker/config.json`. This file is structured in an identical way compared to Podman's authentication file.

.Sample Docker configuration file.
[source,json]
----
{
	"auths": {
		"registry.example.com": {
			"auth": "bGV4OnRlc3Q="
		}
	}
}
----

== Maven Settings
[#mavensettings]
:navtitle: Maven Settings

When a registry that is being used, is neither found in the Podman authentication file, nor the Docker configuration file, then this plugin will attempt to authenticate those registries using information available in the Maven Settings file. Therefore, you must configure the registries in your Maven settings file.

WARNING: The id of the server **must** match the registries configured in the plugin (see below). The plugin will fail if credentials are missing for any of the provided registries.

WARNING: This plugin will also fail if there are no registries configured, but authentication is not skipped. Please refer to the table below for all configuration options.

.Excerpt of a Maven Settings file.
[source,XML]
----
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          https://maven.apache.org/xsd/settings-1.0.0.xsd">

    <servers>
        <server>
            <id>container-registry.host.com</id>
            <username>username</username>
            <password>password</password>
        </server>
        <server>
            <id>container-registry.anotherhost.com:12345</id>
            <username>username</username>
            <password>{gsuybjVYiL4HK1S++3xiE9sHnHtzRGBlajGkQE5IH78=}</password> <!--.-->
        </server>
    </servers>

    <!-- Other settings omitted -->

</settings>
----
<.> Both encrypted and unencrypted passwords are supported.